<?php
if(!defined('PUBLIC_ACCESS')) die('Fuck off - You cant access scripts directly fool !');
$mood = array(
array('id'=> '1', 'name'=> 'is feeling neutral', 'image'=> 'noexpression.gif'),
array('id'=> '2', 'name'=> 'is feeling bad', 'image'=> 'wall.gif'),
array('id'=> '3', 'name'=> 'is feeling good', 'image'=> 'grin.gif'),
array('id'=> '4', 'name'=> 'is feeling tired', 'image'=> 'yawn.gif'),
array('id'=> '5', 'name'=> 'is feeling angry', 'image'=> 'angry.gif'),
array('id'=> '6', 'name'=> 'in wub', 'image'=> 'wub.gif'),
array('id'=> '7', 'name'=> 'is feeling sad', 'image'=> 'wavecry.gif'),
array('id'=> '8', 'name'=> 'is feeling silly', 'image'=> 'clown.gif'),
array('id'=> '9', 'name'=> 'in love', 'image'=> 'love.gif'),
array('id'=> '10', 'name'=> 'is a pirate', 'image'=> 'pirate.gif'),
array('id'=> '11', 'name'=> 'is feeling like ranting', 'image'=> 'rant.gif'),
array('id'=> '12', 'name'=> 'is feeling devilish', 'image'=> 'devil.gif'),
array('id'=> '13', 'name'=> 'is feeling yucky', 'image'=> 'yucky.gif'),
array('id'=> '14', 'name'=> 'yarrr matey', 'image'=> 'pirate2.gif'),
array('id'=> '15', 'name'=> 'is feeling happy', 'image'=> 'smile1.gif'),
array('id'=> '16', 'name'=> 'is feeling like a tease', 'image'=> 'tease.gif'),
array('id'=> '17', 'name'=> 'is feeling awesome', 'image'=> 'w00t.gif'),
array('id'=> '18', 'name'=> 'is feeling bananas', 'image'=> 'bananadance.gif'),
array('id'=> '19', 'name'=> 'is drinking with friends', 'image'=> 'beer2.gif'),
array('id'=> '20', 'name'=> 'is drinking', 'image'=> 'beer.gif'),
array('id'=> '21', 'name'=> 'is feeling like an angel', 'image'=> 'angel.gif'),
array('id'=> '22', 'name'=> 'is feeling bossy', 'image'=> 'cigar.gif'),
array('id'=> '23', 'name'=> 'needs to spew', 'image'=> 'spew2.gif'),
array('id'=> '24', 'name'=> 'is feeling like crying', 'image'=> 'sob.gif'),
array('id'=> '25', 'name'=> 'is dancing', 'image'=> 'mml.gif'),
array('id'=> '26', 'name'=> 'is feeling crazy', 'image'=> 'crazy.gif'),
array('id'=> '27', 'name'=> 'is drunk', 'image'=> 'drunk.gif'),
array('id'=> '28', 'name'=> 'has gone fishing', 'image'=> 'fishing.gif'),
array('id'=> '29', 'name'=> 'is having fun', 'image'=> 'fun.gif'),
array('id'=> '30', 'name'=> 'is feeling like a winner', 'image'=> 'hooray.gif'),
array('id'=> '31', 'name'=> 'is feeling innocent', 'image'=> 'innocent.gif'),
array('id'=> '32', 'name'=> 'is laughing his arse off', 'image'=> 'rofl2.gif'),
array('id'=> '33', 'name'=> 'is feeling like kissing', 'image'=> 'kissing2.gif'),
array('id'=> '34', 'name'=> 'is a clown', 'image'=> 'finger.gif'),
array('id'=> '35', 'name'=> 'is feeling like a king', 'image'=> 'king.gif'),
array('id'=> '36', 'name'=> 'is into the music', 'image'=> 'music.gif'),
array('id'=> '37', 'name'=> 'is a ninja', 'image'=> 'ninja.gif'),
array('id'=> '38', 'name'=> 'is feeling old', 'image'=> 'oldtimer.gif'),
array('id'=> '39', 'name'=> 'is feeling like a pimp', 'image'=> 'pimp.gif'),
array('id'=> '40', 'name'=> 'is feeling like shit', 'image'=> 'shit.gif'),
array('id'=> '41', 'name'=> 'is feeling sly', 'image'=> 'sly.gif'),
array('id'=> '42', 'name'=> 'is feeling smart', 'image'=> 'smart.gif'),
array('id'=> '43', 'name'=> 'is stoned', 'image'=> 'smokin.gif'),
array('id'=> '44', 'name'=> 'is feeling weird', 'image'=> 'weirdo.gif'),
array('id'=> '45', 'name'=> 'Is a feeling devious', 'image'=> 'spiteful.gif'),
array('id'=> '46', 'name'=> 'Is feeling cheeky', 'image'=> 'moonie.gif'),
array('id'=> '47', 'name'=> 'is feeling stoned', 'image'=> 'spliffy.gif'),
array('id'=> '48', 'name'=> 'is a raving loony', 'image'=> 'madraver.gif'),
array('id'=> '49', 'name'=> 'is feeling pish', 'image'=> 'pish.gif'),
array('id'=> '50', 'name'=> 'is unsure', 'image'=> 'pardon.gif'),
array('id'=> '51', 'name'=> 'is shocked', 'image'=> 'blink.gif'),
array('id'=> '52', 'name'=> 'Wants to get high', 'image'=> 'Line.gif'),
);
?>