// JavaScript Document
function uncheck_all()
  {
  document.getElementById("check1").checked=false;
  document.getElementById("check3").checked=false;
  document.getElementById("check5").checked=false;
  document.getElementById("check7").checked=false;
  document.getElementById("check9").checked=false;
  document.getElementById("check12").checked=false;
  document.getElementById("check14").checked=false;
  document.getElementById("check16").checked=false;
  document.getElementById("check18").checked=false;
  document.getElementById("check19").checked=false;
  document.getElementById("check21").checked=false;
  document.getElementById("check23").checked=false;
  document.getElementById("check25").checked=false;
  document.getElementById("check27").checked=false;
  document.getElementById("check30").checked=false;
  document.getElementById("check32").checked=false;
  document.getElementById("check34").checked=false;
  document.getElementById("check36").checked=false;
  document.getElementById("check2").checked=false;
  document.getElementById("check4").checked=false;
  document.getElementById("check6").checked=false;
  document.getElementById("check8").checked=false;
  document.getElementById("check10").checked=false;
  document.getElementById("check11").checked=false;
  document.getElementById("check13").checked=false;
  document.getElementById("check15").checked=false;
  document.getElementById("check17").checked=false;
  document.getElementById("check20").checked=false;
  document.getElementById("check22").checked=false;
  document.getElementById("check24").checked=false;
  document.getElementById("check26").checked=false;
  document.getElementById("check28").checked=false;
  document.getElementById("check29").checked=false;
  document.getElementById("check31").checked=false;
  document.getElementById("check33").checked=false;
  document.getElementById("check35").checked=false;
  }
  
var form='casino3' //Give the form name here

function SetChecked(val,chkName) {
dml=document.forms[form];
len = dml.elements.length;
var i=0;
for( i=0 ; i<len ; i++) {
if (dml.elements[i].name==chkName) {
dml.elements[i].checked=val;
}
}
}

function set_red()
  {
  uncheck_all();
  document.getElementById("check1").checked=true;
  document.getElementById("check3").checked=true;
  document.getElementById("check5").checked=true;
  document.getElementById("check7").checked=true;
  document.getElementById("check9").checked=true;
  document.getElementById("check12").checked=true;
  document.getElementById("check14").checked=true;
  document.getElementById("check16").checked=true;
  document.getElementById("check18").checked=true;
  document.getElementById("check19").checked=true;
  document.getElementById("check21").checked=true;
  document.getElementById("check23").checked=true;
  document.getElementById("check25").checked=true;
  document.getElementById("check27").checked=true;
  document.getElementById("check30").checked=true;
  document.getElementById("check32").checked=true;
  document.getElementById("check34").checked=true;
  document.getElementById("check36").checked=true;
  }
function set_black()
  {
  uncheck_all()
  document.getElementById("check2").checked=true;
  document.getElementById("check4").checked=true;
  document.getElementById("check6").checked=true;
  document.getElementById("check8").checked=true;
  document.getElementById("check10").checked=true;
  document.getElementById("check11").checked=true;
  document.getElementById("check13").checked=true;
  document.getElementById("check15").checked=true;
  document.getElementById("check17").checked=true;
  document.getElementById("check20").checked=true;
  document.getElementById("check22").checked=true;
  document.getElementById("check24").checked=true;
  document.getElementById("check26").checked=true;
  document.getElementById("check28").checked=true;
  document.getElementById("check29").checked=true;
  document.getElementById("check31").checked=true;
  document.getElementById("check33").checked=true;
  document.getElementById("check35").checked=true;
  }
function set_1to18()
  {
  uncheck_all()
  document.getElementById("check1").checked=true;
  document.getElementById("check2").checked=true;
  document.getElementById("check3").checked=true;
  document.getElementById("check4").checked=true;
  document.getElementById("check5").checked=true;
  document.getElementById("check6").checked=true;
  document.getElementById("check7").checked=true;
  document.getElementById("check8").checked=true;
  document.getElementById("check9").checked=true;
  document.getElementById("check10").checked=true;
  document.getElementById("check11").checked=true;
  document.getElementById("check12").checked=true;
  document.getElementById("check13").checked=true;
  document.getElementById("check14").checked=true;
  document.getElementById("check15").checked=true;
  document.getElementById("check16").checked=true;
  document.getElementById("check17").checked=true;
  document.getElementById("check18").checked=true;
  }
function set_19to36()
  {
  uncheck_all()
  document.getElementById("check19").checked=true;
  document.getElementById("check20").checked=true;
  document.getElementById("check21").checked=true;
  document.getElementById("check22").checked=true;
  document.getElementById("check23").checked=true;
  document.getElementById("check24").checked=true;
  document.getElementById("check25").checked=true;
  document.getElementById("check26").checked=true;
  document.getElementById("check27").checked=true;
  document.getElementById("check28").checked=true;
  document.getElementById("check29").checked=true;
  document.getElementById("check30").checked=true;
  document.getElementById("check31").checked=true;
  document.getElementById("check32").checked=true;
  document.getElementById("check33").checked=true;
  document.getElementById("check34").checked=true;
  document.getElementById("check35").checked=true;
  document.getElementById("check36").checked=true;
  }
function set_even()
  {
  uncheck_all()
  document.getElementById("check2").checked=true;
  document.getElementById("check4").checked=true;
  document.getElementById("check6").checked=true;
  document.getElementById("check8").checked=true;
  document.getElementById("check10").checked=true;
  document.getElementById("check12").checked=true;
  document.getElementById("check14").checked=true;
  document.getElementById("check16").checked=true;
  document.getElementById("check18").checked=true;
  document.getElementById("check20").checked=true;
  document.getElementById("check22").checked=true;
  document.getElementById("check24").checked=true;
  document.getElementById("check26").checked=true;
  document.getElementById("check28").checked=true;
  document.getElementById("check30").checked=true;
  document.getElementById("check32").checked=true;
  document.getElementById("check34").checked=true;
  document.getElementById("check36").checked=true;
  }
function set_odd()
  {
  uncheck_all()
  document.getElementById("check1").checked=true;
  document.getElementById("check3").checked=true;
  document.getElementById("check5").checked=true;
  document.getElementById("check7").checked=true;
  document.getElementById("check9").checked=true;
  document.getElementById("check11").checked=true;
  document.getElementById("check13").checked=true;
  document.getElementById("check15").checked=true;
  document.getElementById("check17").checked=true;
  document.getElementById("check19").checked=true;
  document.getElementById("check21").checked=true;
  document.getElementById("check23").checked=true;
  document.getElementById("check25").checked=true;
  document.getElementById("check27").checked=true;
  document.getElementById("check29").checked=true;
  document.getElementById("check31").checked=true;
  document.getElementById("check33").checked=true;
  document.getElementById("check35").checked=true;
  }
function set_1stcolumn()
  {
  uncheck_all()
  document.getElementById("check1").checked=true;
  document.getElementById("check4").checked=true;
  document.getElementById("check7").checked=true;
  document.getElementById("check10").checked=true;
  document.getElementById("check13").checked=true;
  document.getElementById("check16").checked=true;
  document.getElementById("check19").checked=true;
  document.getElementById("check22").checked=true;
  document.getElementById("check25").checked=true;
  document.getElementById("check28").checked=true;
  document.getElementById("check31").checked=true;
  document.getElementById("check34").checked=true;
  }
function set_2ndcolumn()
  {
  uncheck_all()
  document.getElementById("check2").checked=true;
  document.getElementById("check5").checked=true;
  document.getElementById("check8").checked=true;
  document.getElementById("check11").checked=true;
  document.getElementById("check14").checked=true;
  document.getElementById("check17").checked=true;
  document.getElementById("check20").checked=true;
  document.getElementById("check23").checked=true;
  document.getElementById("check26").checked=true;
  document.getElementById("check29").checked=true;
  document.getElementById("check32").checked=true;
  document.getElementById("check35").checked=true;
  }
function set_3rdcolumn()
  {
  uncheck_all()
  document.getElementById("check3").checked=true;
  document.getElementById("check6").checked=true;
  document.getElementById("check9").checked=true;
  document.getElementById("check12").checked=true;
  document.getElementById("check15").checked=true;
  document.getElementById("check18").checked=true;
  document.getElementById("check21").checked=true;
  document.getElementById("check24").checked=true;
  document.getElementById("check27").checked=true;
  document.getElementById("check30").checked=true;
  document.getElementById("check33").checked=true;
  document.getElementById("check36").checked=true;
  }
function set_1to12()
  {
  uncheck_all()
  document.getElementById("check1").checked=true;
  document.getElementById("check2").checked=true;
  document.getElementById("check3").checked=true;
  document.getElementById("check4").checked=true;
  document.getElementById("check5").checked=true;
  document.getElementById("check6").checked=true;
  document.getElementById("check7").checked=true;
  document.getElementById("check8").checked=true;
  document.getElementById("check9").checked=true;
  document.getElementById("check10").checked=true;
  document.getElementById("check11").checked=true;
  document.getElementById("check12").checked=true;
  }
function set_13to24()
  {
  uncheck_all()
  document.getElementById("check13").checked=true;
  document.getElementById("check14").checked=true;
  document.getElementById("check15").checked=true;
  document.getElementById("check16").checked=true;
  document.getElementById("check17").checked=true;
  document.getElementById("check18").checked=true;
  document.getElementById("check19").checked=true;
  document.getElementById("check20").checked=true;
  document.getElementById("check21").checked=true;
  document.getElementById("check22").checked=true;
  document.getElementById("check23").checked=true;
  document.getElementById("check24").checked=true;  
  }
function set_25to36()
  {
  uncheck_all()
  document.getElementById("check25").checked=true;
  document.getElementById("check26").checked=true;
  document.getElementById("check27").checked=true;
  document.getElementById("check28").checked=true;
  document.getElementById("check29").checked=true;
  document.getElementById("check30").checked=true;
  document.getElementById("check31").checked=true;
  document.getElementById("check32").checked=true;
  document.getElementById("check33").checked=true;
  document.getElementById("check34").checked=true;
  document.getElementById("check35").checked=true;
  document.getElementById("check36").checked=true;  
  }
